export const create_obj = {
    code:0,
    message:'成功',
    data:[
        {
        id:'disk-dmgebkqq843caved',
        name:'通用策略',
        productType:[
            {
                id:'ecs',
                name:'云服务器ECS',
                rules:[
                    {
                        name:'cpu使用率',
                        level_name:['Host.cpu.total'],
                        type:'1',
                        level:[
                            {
                                range:'>=',
                                num:'80',
                                cycle_time:'1',
                                cycle_num:'15',
                                alram_type:'serious',
                                notice:["短信","邮箱"]
                            },
                            {
                                range:'>=',
                                num:'50',
                                cycle_time:'15',
                                cycle_num:'1',
                                alram_type:'ordinary',
                                notice:["短信"]
                            },
                        ]
                        
                    },
                    {
                        name:'磁盘使用率',
                        event_type:'abnormal',
                        type:'2',
                        event_name:['loss'],
                        alram_type:'ordinary',
                        notice:["短信"]
                    }
                ]
            },
            {
                id:'gpu',
                name:'GPU',
                rules:[
                    {
                        name:'GPU使用率',
                        level_name:'Host.cpu.total',
                        type:'1',
                        level:[
                            {
                                range:'>=',
                                num:'80',
                                cycle_time:'1',
                                cycle_num:'15',
                                alram_type:'serious',
                                notice:["短信","邮箱"]
                            },
                            {
                                range:'>=',
                                num:'50',
                                cycle_time:'15',
                                cycle_num:'1',
                                alram_type:'ordinary',
                                notice:["短信"]
                            },
                        ]
                        
                    },
                    {
                        name:'GPU磁盘占有率',
                        event_type:'abnormal',
                        type:'2',
                        event_name:['loss','diskSpaceRunOut'],
                        alram_type:'ordinary',
                        notice:["短信"]
                    }
                ]
            }
        ]
    }]
}
export const productList = [
    {
        id:'ecs',
        name:'云服务器ECS'
    },
    {
        id:'gpu',
        name:'GPU'
    },
    {
        id:'slb',
        name:'负载均衡'
    },
    {
        id:'vpc',
        name:'私有网络VPC'
    },
    {
        id:'safe',
        name:'安全组'
    },
]
export const level_list=[
    {
        value:'host',
        label:'主机',
        children:[
            {
                value:'Host.cpu.total',
                label:'Host.cpu.total'
            },
            {
                value:'Host.cpu.idle',
                label:'Host.cpu.idle'
            },
            {
                value:'Host.mem.usedutilization',
                label:'Host.mem.usedutilization'
            },
            {
                value:'Host.mem.freeutilization',
                label:'Host.mem.freeutilization'
            },
        ]

    },
    {
        value:'net',
        label:'网络',
        children:[
            {
                value:'net.cpu.total',
                label:'net.cpu.total'
            },
            {
                value:'net.cpu.idle',
                label:'net.cpu.idle'
            },
            {
                value:'net.mem.usedutilization',
                label:'net.mem.usedutilization'
            },
            {
                value:'net.mem.freeutilization',
                label:'net.mem.freeutilization'
            },
        ]
    },
    {
        value:'disk',
        label:'磁盘',
        children:[
            {
                value:'disk.cpu.total',
                label:'disk.cpu.total'
            },
            {
                value:'disk.cpu.idle',
                label:'disk.cpu.idle'
            },
            {
                value:'disk.mem.usedutilization',
                label:'disk.mem.usedutilization'
            },
            {
                value:'disk.mem.freeutilization',
                label:'disk.mem.freeutilization'
            },
        ]
    },
    {
        value:'gpu',
        label:'GPU',
        children:[
            {
                value:'gpu.cpu.total',
                label:'gpu.cpu.total'
            },
            {
                value:'gpu.cpu.idle',
                label:'gpu.cpu.idle'
            },
            {
                value:'gpu.mem.usedutilization',
                label:'gpu.mem.usedutilization'
            },
            {
                value:'gpu.mem.freeutilization',
                label:'gpu.mem.freeutilization'
            },
        ]
    },
]
export const range_list=[
    {id:'>=',title:'>='},
    {id:'<=',title:'<='},
    {id:'>',title:'>'},
    {id:'<',title:'<'},
]
export const cycle_time=[
    {
        id:'1',
        title:'1分钟一个周期',
    },
    {
        id:'15',
        title:'15分钟一个周期',
    },
    {
        id:'30',
        title:'30分钟一个周期',
    },
    {
        id:'60',
        title:'60分钟一个周期',
    },
]
export const cycle_num=[
    {
        id:'1',
        title:'持续1个周期',
    },
    {
        id:'3',
        title:'持续3个周期',
    },
    {
        id:'5',
        title:'持续5个周期',
    },
    {
        id:'10',
        title:'持续10个周期',
    },
    {
        id:'15',
        title:'持续15个周期',
    },
    {
        id:'30',
        title:'持续30个周期',
    },
]
export const alarm_type=[
    {
        id:'serious',
        title:'严重',
    },
    {
        id:'warning',
        title:'警告',
    },
    {
        id:'ordinary',
        title:'普通',
    },
]
export const notice_list = ["邮箱","短信","微信"]
export const event_type=[
    {
        id:'abnormal',
        title:'异常事件',
    },
    {
        id:'success',
        title:'成功事件',
    },
    {
        id:'error',
        title:'错误事件',
    },
]
export const event_name=[
    {
        id:'outage',
        title:'宕机',
    },
    {
        id:'memoryOverload',
        title:'内存使用过载',
    },
    {
        id:'diskReadOnly',
        title:'磁盘只读',
    },
    {
        id:'IOerror',
        title:'IO错误',
    },
    {
        id:'diskSpaceRunOut',
        title:'磁盘空间耗尽',
    },
    {
        id:'loss',
        title:'丢包',
    },
    {
        id:'kernelError',
        title:'内核异常',
    },
]